### ISSUE TITLE
Add section on Super Theme tutorial explaining how to test with Hammer VM

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-design-system#102]

**Comment by adamjohnson** [comment]
Maybe slightly off topic, but...

What's the plan for integrating hammer-vm and the requisite mock_data for this project? 

For reference, right now I'd say we have about 10% of the recommended mock_data (masthead, nav, some hero, some footer).

Do you have plans to go beyond this? Is it even possible/probable? What does "done" look like for mock_data?

Hammer is listed under the Collaborative heading in [Principles - WVU Design System website](https://designsystem.sandbox.wvu.edu/principles).
