### ISSUE TITLE
Add ARIA labels to main header, backpage header, breadcrumbs

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-design-system#109]

**Comment by adamjohnson** [comment]
Why add `aria-label="masthead"` to the `<header>` tag? Are there multiple `<header>` tags? 

https://github.com/wvuweb/wvu-design-system/blob/master/views/layouts/default.html#L42

If not, `aria-label` can be omitted.

**Comment by adamglenn** [comment]
It does when you have a backpage header. I can make it dependent.

**Comment by adamglenn** [comment]
Unless it is more appropriate to use a different HTML tag in either situation?
