### ISSUE TITLE
Need a custom data slot for header's utility classes

### ISSUE THREAD

**Issue by sarahgibbons** [wvuweb/wvu-design-system#152]
Similar to _classes_wvu_backpage_header__h1_, having one location to add utility classes site-wide to edit background-header styles would help make it easier to be consistent.

**Comment by adamglenn** [comment]
Note, in order to use this you need a `classes_wvu_backpage_header` data attribute in your site data and your `default.html` view needs to reference `v2/wvu-backpage-header` instead of just `wvu-backpage-header`.
