### ISSUE TITLE
Featurettes CleanSlate Component doesn't work

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system#166]
## Steps to reproduce the issue

  1. Log into CleanSlate and navigate to [a site](https://cleanslate.wvu.edu/sites/1225/pages) that uses the design system.
  1. Go to Pages > Properties > Custom Data
  1. Add the [Featurettes Component](https://designsystem.wvu.edu/components/featurettes) to a slot. Set the Slot Limit to 3 (or any number).
  1. Save the Page Properties and open the page to edit.

## Results

Featurettes do not show. The featurette's headline and other editable regions show; however, the columns do not show.

## Expected Results

The featurettes columns should show for featurettes. 

cc @ktduong & @rebecca-patton

**Comment by adamglenn** [comment]
This is a problem with the documentation. You have to add a label to each page you want to display in a featurette, so the featurette knows what to display e.g. `{slug-of-page-you-want-it-to-display-on}-featurettes-{instance-number}` i.e. `home-featurettes-1' if you want to add featurettes in the meantime.

**Comment by adamjohnson** [comment]
> Also note that the new featurette component replaces the old “polyptych” patterns. These patterns allowed the designer to specify a number of panels that each contained editable regions (for the thumbnail image, photo, etc.). Now you just use a featurettes component and **set its style to “Editable regions”** in the Super Theme or the featurettesStyle to editable-regions.

From [How Featurettes Work](https://designsystem.wvu.edu/tutorials/how-featurettes-work).

I only needed a triptych, not necessarily to pull pages. Switching the style to "Editable regions" was the key part.

Thank you for the help, especially on your day off.

**Comment by rebecca-patton** [comment]
I'm trying to pass variables to the partials manually, and the columns still aren't showing up for me. 

## Steps to reproduce the issue
Log into CleanSlate and navigate to a site that uses the design system.
Open a page template (i.e. frontpage.html) in your code editor. 
Insert the Featurettes partial and variables after the site data:

<r:set_var name="componentLimit" value="4" />
<r:set_var name="componentFeaturettesStyle" value="editable-regions" />
<r:partial name="components/wvu-featurettes" theme="University Relations: WVU Design System" />

Commit changes and update the theme in CleanSlate.

## Results
Featurettes do not show. The featurette's headline and other editable regions show; however, the columns do not show.

## Expected Results
The featurettes columns should show for featurettes.

**Comment by adamglenn** [comment]
K, I'll take a look tomorrow.

**Comment by adamglenn** [comment]
So I screwed up the variable names on this docs page: https://designsystem.wvu.edu/tutorials/building-templates-using-shared-partials (I assume that is what you were referencing)

Should be:

```<r:set_var name="limit" value="4" />
<r:set_var name="featurettesStyle" value="editable-regions" />
<r:partial name="components/wvu-featurettes" theme="University Relations: WVU Design System" />```

I have updated the docs: https://designsystem.wvu.edu/tutorials/building-templates-using-shared-partials?=53
