### ISSUE TITLE
Improve Implementation Notes for featurettes...

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-design-system#168]
Should explain the difference between featurettes that pull items from pages vs. editable regions, as well as how to label pages to get their content to display in a featurette.

**Comment by adamjohnson** [comment]
A thought: the reason I thought the featurettes component was broken (#166) was because they didn't show anything in their default state (aka I selected Featurettes in `Slot X`). 

Would it be feasable to make the `Editable Region` Featurette Style the default style?
