### ISSUE TITLE
Enable header background image labels for 2nd level/child pages

### ISSUE THREAD

**Issue by rebecca-patton** [wvuweb/wvu-design-system#177]
Let the user label images in CleanSlate for being header background images on child pages (so they can match/coordinate with parent pages).

**Comment by rebecca-patton** [comment]
Well, this seems to be working now! 

Some combination of removing/adding the image label, saving the file properties and saving the page properties seems to have pushed it through. Not sure what the best order/sequence of events is.

**Comment by adamglenn** [comment]
@rebecca-patton Impossible! I don't think there is code in there to do that unless I just copied over from the old Super Theme. Will double-check tomorrow.
