### ISSUE TITLE
Profile images not pulling to Profiles component

### ISSUE THREAD

**Issue by rebecca-patton** [wvuweb/wvu-design-system#185]
Need further documentation on how to get profile photo to pull to a Profiles component (photo is showing on individual Profile component). 

I also cannot get the subnav component to work on the same page as the Profiles component.

https://mindfit.sandbox.wvu.edu/contact/meet-the-staff

**Comment by adamglenn** [comment]
This is another thing I didn’t copy over from the old documentation. I have updated it here: https://designsystem.wvu.edu/tutorials/creating-a-site-using-super-theme?=4 the URL of the file has to follow a certain format. Will add it to the implementation notes ASAP. Thanks for your help with all of this. I know it is frustrating ;) but I think with your help we can improve it a great deal.

**Comment by adamglenn** [comment]
So I made it so for the profiles component, it will only get the margin-x auto if it is used as a full-width block. To use it with a subnav, what you want to do is put it in a backpage-main (this is if you're using Super Theme). So you would set the display context as backpage-main-{instance-number}, then add the subnav to another slot with a display context of sidebar-{instance-number}. Note, this does not work with shared partials that are hard-coded in your template, as I haven't figured out how to do component inception that way (yet). So in that case you'd make a custom component that combines the profiles with sidebar or something like that.
