### ISSUE TITLE
Unable to change page template after page is created with default

### ISSUE THREAD

**Issue by sarahgibbons** [wvuweb/wvu-design-system#197]
I created a page meant to use the Profile template, but hit save before changing it from Backpage. Went to properties before the page was edited or published, and changed it to the Profile template. When I edit the page, it's still displaying the Backpage template. 

I'm working on the Office of Human Research Protections and the page I'm referring to is /about/staff/melissa-himes.

**Comment by adamglenn** [comment]
Okay, I think what happens here is that when the page is initially set to 'backpage', it inserts a 'backpage' component into slot 1. So even if you change the page template, whatever is in slot 1 remains there. So even if you change the template to Profile, you still have to go in and change slot 1 to use the profile component. Will have to figure out something for this, but for now that's what you will have to do.

**Comment by adamglenn** [comment]
This is now (sort of) fixed. Now the default component will switch when you change templates, assuming you have not added any components to the page's slots.
