### ISSUE TITLE
Upgrade to Gulp v4?

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system#198]
@dustinmazon asked if we should consider upgrading to Gulp v4 since we're overhauling a lot of things. 

What do people think about this?

I think upgrading is generally a good idea; however, most of the gulp ecosystem has not moved to the [Gulp v4 syntax](https://gulpjs.com/docs/en/getting-started/creating-tasks). Here's [another peek](https://github.com/thecodercoder/frontend-boilerplate/blob/master/gulpfile.js) at a Gulp v4 syntax with ES6. 

Gulp has kept the `.task()` API, but recommends against using it:

> Reminder: This API isn't the recommended pattern anymore - [export your tasks](https://gulpjs.com/docs/en/getting-started/creating-tasks).

This means people could _probably_ still copy and paste tasks from various plugins' README's and still work.

Curious to hear @zeroedin's thoughts too.

**Comment by zeroedin** [comment]
Short answer: Yes upgrade.

**Comment by zeroedin** [comment]
Supplemental note:

To support forward moving targets, installing [NVM](https://github.com/nvm-sh/nvm) or [NVM-Windows](https://github.com/coreybutler/nvm-windows) should become the default as a dependency management tool in our kit. 

We end up supporting projects longer then the LTS cycle for NodeJS.  In order to get a better grip on when the node packages where installed we should be using `.nvmrc` files and pinning the projects in `.package.json` using:

```
"engineStrict": true,
"engines": {
    "node": ">=xx.xx.xx"
 }
```

A working example of this can be found in the [mountaineer nation day](https://bitbucket.org/wvudigital/ur-mountaineer-nation-day/src/master/package.json) cleanslate theme in bitbucket.

You most likely will want to release a breaking change version when Gulp 4 is introduced

**Comment by zeroedin** [comment]
test

**Comment by adamjohnson** [comment]
Heads up: I have upgraded the Gulpfile to use the v4 syntax and Node ^12.13.1. You all should pull down these changes and test it out.

Some things to keep in mind:

  * If you use `nvm`, you'll need to install Node v12.13.1 by typing `nvm install v12.13.1`, then type `nvm use v12.13.1`.
  * After that, delete your entire `node_modules` folder.
  * You'll probably have to install gulp globally again: `npm install -g gulp-cli`
  * Then run `npm ci`.
  * Then run `gulp` and see if everything is working for you.

Some things we can talk about to decide if this approach is agreeable:

  * I'm importing specific gulp API's so that we can type `series()` instead of `gulp.series()`. See [lines 3-6](https://github.com/wvuweb/wvu-design-system/blob/c709b1cf65913398caff4028eb5e07232e4c36e5/gulpfile.js#L3-L6) in the gulpfile.
    * This is likely the most "controversial" as we may see docs using `gulp.series()` more than `series()`. Let me know what you think.
  * I've abstracted the paths to their own object since we have to pass them to multiple functions (DRY).
  * I specified ^12.13.1 in `package.json` and did not lock node/npm to a specific version. This is the same as 12.x.x where the `13` means 13+.
  * I purposefully didn't import `task()` on line 6, but this might bite us later. See below.

One thing to keep in mind is that gulp [recommends not using `.task()` anymore](https://gulpjs.com/docs/en/api/task)--but you see it everywhere, even in v4 migration guides. Just a heads up.

FWIW, I referenced the following when going through this process:

  * [TheCoderCoder Frontend Boilerplate Gulpfile](https://github.com/thecodercoder/frontend-boilerplate/blob/master/gulpfile.js)
  * [Webstoemp Gulpfile Gist](https://gist.github.com/jeromecoupe/0b807b0c1050647eb340360902c3203a)
  * [gulp-sass gulp v4 pull request](https://github.com/dlmanning/gulp-sass/pull/750/files)

@adamglenn when/if we find these changes satisfactory, these deserve a release (perhaps a major release?). Might go well with #208 / #204.
