### ISSUE TITLE
Using the profile component, the email address overlaps the bio text on medium-width screens

### ISSUE THREAD

**Issue by rebecca-patton** [wvuweb/wvu-design-system#200]
See the issue here:
https://mindfit.wvu.edu/contact/meet-the-staff/dan-long

My solution, for now, here:
https://mindfit.wvu.edu/contact/meet-the-staff/jennifer-mandeville

Removed 'simple' from email editable region in _wvu-contact-info.html, then added zero-width space (&#8203;) at the point where I wanted the email address to break. Adding <br> doesn't work because it also inserts an un-needed break in the email address on the profiles index page.

**Comment by adamglenn** [comment]
Fixed this in another commit. Forgot about this one.
