### ISSUE TITLE
Move custom data attributes used on all templates to the config.yml file

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system#204]
## Steps to reproduce the issue

Look at any/all templates in the design system. Custom data is repeated over and over in each file.

## Results

This results in having to maintain the same code / custom data in multiple places.

## A better way

Move the shared custom data to the `config.yml` file. Yes, the `config.yml` file regularly holds `custom_site_data`, but a lesser known thing is that it can house `custom_page_data` too!

I ran across this while reading the docs on [custom data](https://cleanslatecms.wvu.edu/how-to/theme-development/custom-data).

This will make the developer experience of dealing with templates much easier (aka not having to scroll through 1,500 lines of custom data on each template). Additionally, it can be managed in one place.

**Comment by adamglenn** [comment]
Well I'll be damned. This seems to work fine on my local CleanSlate. Swear to God I asked Nathan how to do this at one point and he didn't tell me about this.
