### ISSUE TITLE
Thinking about changing the way templates in the Super Theme work...

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-design-system#208]
The standard backpage, blog index, etc. templates should just be templates that only have these particular components in them (a backpage, blog index, etc.), no "slots". Then we could have one template called 'custom', which would have the slots.

I think this would be less confusing and would be less annoying because the way it works now is that if you originally create a page using template A (a backpage, for example), what happens is it just assigns a backpage component to slot one. But if you change the template to template B (a profile, for example), there is no way to automatically change what is in the slot. You have to go back and add a profile component to slot one. As far as I know, there is no way for me to fix this. Shortsightedness on my part.

Making a 'custom' template would also mean we wouldn't have all of the bloated custom data attributes in any template. The standard backpage, blog index, etc. templates wouldn't need them, and I can define the data for the Custom template in the config.yml file.

You would of course always be able to include any component in the Custom template no matter what. So if you still wanted to use Profiles, but combine with other components, instead of using the Profiles template you would just use the Custom template and add a Profiles component to one of the slots.

The other thing to note would be that this would not effect any existing sites, only new sites, because it only affects templates and the config.yml file, not shared components. So we wouldn't have to worry about messing up anyone's existing site.

**Comment by rebecca-patton** [comment]
If someone wanted to add more components after starting with a backpage template without slots, could they change to a custom template without losing what they'd already done? As long as there was a seamless way for people to do that, I think that would be okay.  Not having all those custom data attributes on every page sounds like a good thing. Personally I don't find changing the slots that bad but improving the interface under Custom Data would make it way better.

**Comment by adamglenn** [comment]
Yes, it would be seamless. The templates would have a component in them with instance number of 1. So if the user switched to a custom template, they would just need to make sure and put the default component in there with an instance number of 1 and they would keep the content intact.

**Comment by dustinmazon** [comment]
Go for it. Make a whole lot of sense to me.
