### ISSUE TITLE
Create more visual hierarchy in the custom data attributes window

### ISSUE THREAD

**Issue by TatsuJohnson** [wvuweb/wvu-design-system#210]
I think that it is difficult to quickly understand where one section's options starts and end. 

![Screen Shot 2019-10-11 at 2 41 20 PM](https://user-images.githubusercontent.com/7927516/66676584-dad00b00-ec35-11e9-898a-7846a6d159dc.png)

Maybe something like using rules , switching color backgrounds or cards could help solve this problem.

**Comment by adamglenn** [comment]
This is not going to happen. Nathan is building a theme editor for CleanSlate that will have all of this functionality. At that point we can design this how we want.

**Comment by adamjohnson** [comment]
There is a chance this could be done via CSS attribute selectors:

https://gist.github.com/emmabostian/ed933bc7f9711acdc565f42f1b159407

Someone would have to:

  1. See if it is possible via attribute selectors
  1. Write the appropriate styles.
  1. Share said styles with me.
  1. I add styles to the app.

There are probably some pitfalls, but it _might_ work.

**Comment by adamjohnson** [comment]
[This commit](https://github.com/wvuweb/cleanslate/commit/c85da24d09a4dfca86082ca89d315c1d08da2885) attempts to help fix this issue.

![dashed-line-separators-v2](https://user-images.githubusercontent.com/575865/108574958-b767a680-72e6-11eb-92fd-0c4058c4b12b.png)
