### ISSUE TITLE
Update Twitter Fetcher to use v18.0.3.

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system#212]
The current version is v18.0.2. Changing this to v18.0.3 in `package.json` should do the trick.

**Comment by adamglenn** [comment]
Did this and its saying it doesn't exist.

**Comment by adamjohnson** [comment]
Indeed. It appears to not be published on NPM. I will file an issue with Jason and see if he can [publish a scoped public package](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages).

**Comment by adamjohnson** [comment]
[Request submitted](https://github.com/jasonmayes/Twitter-Post-Fetcher/issues/172#issuecomment-573772951).

FYI: now the latest version is 18.0.4.

**Comment by adamjohnson** [comment]
This package is now up to date [on npmjs.org](https://www.npmjs.com/package/twitter-fetcher). Change the version number to `18.0.4` in the `package.json` file and run `npm install`/`npm update`. Then make sure the new JS file was copied to the `javascripts` folder via `gulp moveJsFiles`.
