### ISSUE TITLE
Question - How to add dropdown menus to primary navigation in Super Theme

### ISSUE THREAD

**Issue by mhaas3** [wvuweb/wvu-design-system#215]
How do I input dropdown menus within my primary navigation in supertheme?

**Comment by adamglenn** [comment]
Enter `true` in the `nav_dropdowns` field in your site’s custom data (Settings > Data). Familiarize yourself with custom site data on this page: https://designsystem.wvu.edu/tutorials/creating-a-site-using-super-theme it has a chart with all the different options.
