### ISSUE TITLE
Update site to include how Featurettes ID are obtained for blog articles

### ISSUE THREAD

**Issue by mr0151** [wvuweb/wvu-design-system#226]
![image](https://user-images.githubusercontent.com/58947254/70920083-f833a380-1fef-11ea-8349-1a8bb6b54f08.png)

**Comment by adamglenn** [comment]
@mr0151 I've updated the documentation: 
![image](https://user-images.githubusercontent.com/1557841/71989520-d6e56200-31ff-11ea-8655-475921bb2d53.png)
Let me know if that makes sense.

**Comment by mr0151** [comment]
@adamglenn Yes, it does.
