### ISSUE TITLE
syntax error in _wvu-slash.scss

### ISSUE THREAD

**Issue by architarious** [wvuweb/wvu-design-system#237]
### Description of problem

I keep getting the following error whenever I try to compile.

Generating JavaScript bundles failed

Parse error on line 1:
-25% + -(1 * 2rem)
--------^
Expecting "SUB", "NUMBER", "LENGTH", "ANGLE", "TIME", "FREQ", "RES", "EMS", "EXS", "CHS", "REMS", "VHS", "VWS", "VMINS", "VMAXS", "PERCENTAGE", "css_value", got unexpected "LPAREN"

### How to fix it

I narrowed it down to either line 82 or 92 in scss/utilities/_wvu-slash.scss, and then made the following changes and it worked fine.

**Change these lines**
82: `left: -($i * $spacer) $global-important;`
92: `top: calc(-25% + -(#{$i} * #{$spacer})) $global-important;`

**To this:**
82: `left: ($i * $spacer)*(-1) $global-important;`
92:  `top: calc(-25% + (#{$i} * #{$spacer})*(-1)) $global-important;`

**Comment by adamglenn** [comment]
@zeroedin fixed this today https://github.com/wvuweb/wvu-design-system/pull/240/commits/66b0ba8c333823ade7aa159502622e0a40aea712
