### ISSUE TITLE
Add quote marks to titles and fix smart apostrophes in Super Theme custom data for major template

### ISSUE THREAD

**Issue by alaina-duty** [wvuweb/wvu-design-system#241]
![screenshot of custom data](https://user-images.githubusercontent.com/61238815/74841959-95b09980-52f7-11ea-88be-cb393194d51d.png)

The out-of-the-box Super Theme has some fields in the custom data in the major template (screenshot attached, taken after I fixed the apostrophes and quotes but I marked where they were). The smart apostrophes and missing quote marks started causing an issue when I started editing the template.

**Comment by adamglenn** [comment]
I must have modified this at some point, but can't tell when. Going to close this for now. If the newer version has issues, let me know and I can re-open.
