### ISSUE TITLE
Correct spelling of wvu-accent--"yellor" to yellow in _wvu.variables.scss

### ISSUE THREAD

**Issue by alaina-duty** [wvuweb/wvu-design-system#242]
![screenshot of color variables](https://user-images.githubusercontent.com/61238815/74844675-ce527200-52fb-11ea-809c-947cc0f676af.png)

In the initial commit for our new site in the Super Theme, line 185 of _wvu-variables.scss had a misspelling of yellow.

**Comment by adamglenn** [comment]
Fixed this one back in December: https://github.com/wvuweb/wvu-design-system/commit/7c2eb4aa707b4950d944a07e32060bb55d20a6e3#diff-dd282ed9dec46e6aa80cee36fbf6eb39

**Comment by adamglenn** [comment]
Nevermind. That must have been when I broke it. Re-opening.
