### ISSUE TITLE
Replace nav with the one from wvu.edu.

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-design-system#25]
Is better for usability. Also restyle the plus sign.

**Comment by adamjohnson** [comment]
FYI I also implemented this in Brand Patterns, starting at v1.5.0 and put a few enhancements in for v1.6.0. 

Commit log starting from July 5th, 2018:

https://github.com/wvuweb/brand-patterns/commits/master

Vendor JS: https://github.com/wvuweb/brand-patterns/blob/master/javascripts/vendor/responsive-nav-dropdown.js

WVU's Custom Dropdown JS: https://github.com/wvuweb/brand-patterns/blob/master/javascripts/responsive-nav-dropdown--custom.js

Relevant Dropdown Sass: https://github.com/wvuweb/brand-patterns/blob/master/scss/1-base/_wvu-nav-dropdowns.scss

☝️ NOTE: Specifically disabling menus beyond the second level for UI/UX reasons (see the comments in that file). I figured people can dig in and enable it if they're really keen on having hover menus for their hover menus.

Relevant HTML: https://github.com/wvuweb/brand-patterns/blob/master/views/patterns/_wvu-nav-dropdowns.html

____________________________

FWIW, I like the `+` and `-` signs for mobile. We're already using arrows to denote the presence of a dropdown, so using another ▶️ would muddy the waters IMO.

**Comment by adamjohnson** [comment]
If you click "Menu" on [Virginia Tech's Homepage](https://vt.edu/index.html), they have a `+` / `×` pattern. Also works well.
