### ISSUE TITLE
Move $enable_keywords out of the default layout

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system#271]
## Steps to reproduce the issue

  1. Open the Design System > Views > Layouts.
  1. Open `default.html`
  1. On [lines 71-78](https://github.com/wvuweb/wvu-design-system/blob/master/views/layouts/default.html#L71-L78), there is code for the [Big Search](https://designsystem.wvu.edu/components/content-patterns/big-search) component.

## Results

This code puts an editable region for keywords for the Big Search component.

## Expected results

Instead of having this in the default layout (and thus having to process the value of the `$enable_keywords` variable and resulting radius code), this should be moved to the [Big Search partial](https://github.com/wvuweb/wvu-design-system/blob/master/views/components/_wvu-big-search.html) and inserted into the layout via `page_js` with `<r:content_for>`.

The hope here is to minimize the amount of processing CleanSlate has to do for every single page; thus, improving performance (in this case, Time to First Byte / Server Response Time). 

This also tightly couples this code together with its component and makes it less confusing as to what it is.

**Comment by adamglenn** [comment]
This code doesn’t apply to pages with the Big Search component, but any page in the site that is searchable by that component. The Big Search searches the keyword editable region of other pages and displays pages with those keywords on a Big Search Results page. So it could be any page that needs the region.

**Comment by adamglenn** [comment]
What should happen is that this code should just be omitted by default and inserted only into themes that use the Big Search, since we are encouraging people to do stuff manually now anyways, and the Big Search is seldom used.

**Comment by adamjohnson** [comment]
Should the custom page data in `config.yml` be removed too, or just the HTML from the default layout?

I suppose I'd vote remove both.

**Comment by adamglenn** [comment]
Both. I just need to add documentation to the Big Search implementation notes.
