### ISSUE TITLE
Create hosted CSS and JS files on static.

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-design-system#43]
This way developers can just link to our file if they don't have to incorporate their own source code.

**Comment by adamjohnson** [comment]
Also be sure to reference static.wvu.edu in the `public/starter-template.html` file.

**Comment by adamglenn** [comment]
We don't need to do this. Most users will be downloading the theme and/or can grab a compiled CSS file from the theme. If this becomes a need, @zeroedin has a method we can use to do it.
