### ISSUE TITLE
Add Fontface Observer back in.

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-design-system#50]

**Comment by adamjohnson** [comment]
Reopening this issue because FFO needs updated and integrated into this project. As of this writing, the files are linked; however, the library is not being used.

**Comment by adamjohnson** [comment]
👆 That last commit was a big one. I figured I would put the commit message here so the paper trail is easier to follow:

> **Update FontFaceObserver. Integrate it into this project. Closes #50.**

> This commit does the following:

>  * Updates FontFaceObserver to v2.1.0.
>  * Deeply integrates FFO into this project. It also accounts for when a user does not load our webfonts from fonts.com, only uses Helvetica Condensed Black & Light only, or doesn't link FFO.
>  * Previously we used Impact as a fallback font for Helvetica Condensed Black. I've changed this to Arial Narrow bolder as it's light years more readable.
>  * FFO will log messages to the console regarding the status of which fonts have or have not loaded.

For reference, whenever you would like to use a font for a component in this project, **use the appropriate utility class or mixin**. Try to avoid using variables directly with `font-family`.

For future reference, FontFaceObserver can be removed when fonts.com [starts supporting](https://www.zachleat.com/web/google-fonts-display/) the `font-display: swap;` CSS property. See current webfont provider support on the table under "Timeline".
