### ISSUE TITLE
Is it worth including Helvetica Neue Roman and Bold in the fonts.com project?

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system#75]
We could shave 42kb off of the fonts.com "expanded" package/"project" if we didn't include Helvetica Neue Roman and Bold.

Since these two weights are so close to Arial, is it worth including these? I know we had previously decided against including these in the fonts.com package.

FWIW, our current minified (not gzipped) CSS size is 312kb.

**Comment by adamglenn** [comment]
I would rather create an intermediate font package and give designers the option of using that. I don't think Helvetica and Arial are that close. CSS file is big, maybe we can get that down. I find it interesting that our pages still get a 98% performance score in Lighthouse, despite the large CSS size/font package size. Wonder if/why Google changed their criteria for evaluating performance?

**Comment by adamglenn** [comment]
Also, maybe I don't think Helvetica and Arial are that close because my eye has been trained to recognize the difference, and a normal user wouldn't be able to tell the difference, but the same could probably be said for Iowan/Georgia. I don't think the user cares. So why draw the line w/Helvetica?

**Comment by adamjohnson** [comment]
We can leave it as it is then. I think having the two options is sufficient. No need to make it more complex by adding a third package.
