### ISSUE TITLE
package-lock.json should not be included in .gitignore

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/wvu-design-system#94]
package-lock.json should not be included in .gitignore.

On this note, we might want to start using `npm ci` instead of `npm install` when initializing a new theme.

`npm install` can mutate the package-lock.json, therefore, changing versions installed on the user's machine.  This should only be done by the repo maintainer or anyone that is updating the dependency chain.

`npm ci` requires the existence of `package-lock.json` and only uses the versions in the lockfile ensuring the same packages are installed in a "known-to-work state" across different computers.

More info: 

https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci

https://docs.npmjs.com/cli/ci

**Comment by zeroedin** [comment]
To illustrate this workflow when you would use what command.

Repo maintainer installing new dependency to wvu-design-system -> `npm install --save some-package`

vs.

Initialization of new theme from the wvu-design-system base -> `npm ci`

vs.

Theme developer adding additional dependencies to their theme chain -> `npm install --save some-other-package`

vs. 

Secondary developer pulling dependencies down to locally develop on a theme -> `npm ci`

**Comment by adamjohnson** [comment]
The README needs updated to say to use `npm ci` instead of `npm install`.

**Comment by adamjohnson** [comment]
Also, be sure to include any special instructions related to `npm run postinstall` in the README. 

Related to #92.

**Comment by adamjohnson** [comment]
This was solved in d50adcaca92fafee8ec63148f958fc4a9d2938f9.
