### ISSUE TITLE
Buy an extended commercial license for Hover.css

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system#95]
This system [uses](https://github.com/wvuweb/wvu-design-system/blob/master/package.json#L18) [Hover.css](https://ianlunn.github.io/Hover/). It requires a paid Extended Commercial license if we plan to bundle it in this system. The license is a one time $18 fee:

https://ianlunn.co.uk/store/hover-css/?attribute_pa_licenses=extended-commercial

@jja006, since you have a P-Card, can you purchase a license for us? 👏

**Comment by adamglenn** [comment]
I have left this off for now. Not sure I like it. Let's figure out something comprehensive for animation at a later date.

**Comment by adamjohnson** [comment]
OK then this should be removed from the [project's dependencies](https://github.com/wvuweb/wvu-design-system/blob/master/package.json#L18).
