### ISSUE TITLE
Twitter fetcher JS has been modified and differs from what's published on Github

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system#98]
This is the modified twitter-fetcher 17.0.3 JS:

https://github.com/wvuweb/wvu-design-system/blob/master/javascripts/vendor/twitterFetcher.js

This is 17.0.3 as seen from their Github repo:

https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/17.0.3/js/twitterFetcher.js

Here's a diff of those two files:

https://www.diffchecker.com/uUZS6qt6

Now that we're pulling this in via NPM, we need to find a more sustainable way to use this script. This likely means:

  1. Updating to the latest version
  1. Using a [custom template](https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/js/exampleUsage.js#L190-L222) for the twitter fetcher output.

As I recall, this script was modified to add `aria-labelledby` for accessibility reasons.

**Comment by zeroedin** [comment]
_wvu-twitter-widget.html

change  `<div id="exampleProfile"></div>` to `<div id="<r:site:data name="twitter_element_id" />"></div>`  in the body of the template making that configurable.  Might even do that per page instead of site.

For the custom callback code, this stays in the template directly so you can use radius tags in the configuration.
```
<r:content_for name="page_js">
  <r:include_javascript name="vendor/twitter-fetcher/twitterFetcher_min" />

  <script type="text/javascript" defer>
    // ##### Simple example 1 #####
    // A simple example to get my latest tweet and write to a HTML element with
    // id "example1". Also automatically hyperlinks URLS and user mentions and
    // hashtags.
    var configProfile = {
      "profile": {"screenName": '<r:site:data name="twitter_handle" />'},
      "domId": '<r:site:data name="twitter_element_id" />',
      "maxTweets": 4,
      "enableLinks": true,
      "showUser": false,
      "showTime": true,
      "showImages": false,
      "showInteraction": false,
      "customCallback": formatTweets,
      "lang": 'en'
    };

    twitterFetcher.fetch(configProfile);

    function formatTweets(tweets) {
        var config = {
          domId: '<r:site:data name="twitter_element_id" />',
          wrap_html_open: '<div class="row">',
          wrap_html_close: '</div>',
          item_html_open: '<div class="col border-left border-wvu-neutral--light-gray">',
          item_html_close: '</div>',
        }

        var x = tweets.length;
        var n = 0;
        var element = document.getElementById(config.domId);
        var html = config.wrap_html_open;
        while (n < x) {
          html += config.item_html_open + tweets[n] + config.item_html_close;
          n++;
        }
        html += config.wrap_html_close;
        element.innerHTML = html;

    }

  </script>
</r:content_for>
```

**Comment by adamjohnson** [comment]
As an addendum to the most recent commit 👆: 

  * The `id` being referenced by the JS is still `exampleProfile`. This should probably change but it's also listed on the Design System Website as `exampleProfile`, so we would want to change them in unison. 
  * The `wvu-twitter-widget.html` partial is set up to be all fancy like the rest of the partials (rename editable regions, include it twice on the page, etc) but I don't think that will work because we're only able to call one Twitter handle via `<r:site:data name="twitter_handle" />`. Something should change. My vote is to make the partial more simple.

Shout out to Steve for the JS help. See the commit for the completed code, it evolved from what's above.
